get http://localhost:3000

###
post http://localhost:3000/register
Content-Type: application/json

{
    "username": "Victor",
    "email": "laukeymwaura@gmail.com",
    "password": "123456"
}

###
post http://localhost:3000/login
Content-Type: application/json

{
    "username": "Victor",  
    "password": "123456"
}

###
post http://localhost:3000/add-posts
Content-Type: application/json

{
   "url" : "https://www.instagram.com/static/images/homepage/screenshots/screenshot3.png/94edb770accf.png",
   "heading": "instagram",
   "description": "Working",
   "likes": 3,
   "userID": 1  
}   

###
post http://localhost:3000/add-comments/2
Content-Type: application/json

{
    "comment": "This is a comment",
    "userID": 1,
    "postID": 2
}

###
post http://localhost:3000/post/comments/reply/1
Content-Type: application/json

{
    "reply": "This is a reply",
    "userID": 1,
    "commentID": 1
}

###
get http://localhost:3000/post/comments/1