get http://localhost:3000

###
post http://localhost:3000/register
Content-Type: application/json

{
    "username": "Vicky",
    "email": "laukey3",
    "password": "123456"
}

###
post http://localhost:3000/login
Content-Type: application/json

{
    "username": "Vicky",  
    "password": "123456"
}